name: MERN DevSecOps Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  FRONTEND_REPO: frontend
  BACKEND_REPO: backend
  IMAGE_TAG: ${{ github.sha }}
  CLUSTER_NAME: mern-eks

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --verbose --redact --exit-code 1
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd server && npm install
          cd ../client && npm install

  scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "quickChat"
          path: "."
          format: "ALL"
          failOnCVSS: 4

      - name: Checkov - Scan Kubernetes Manifests
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./k8
          framework: kubernetes
          output_format: cli
          soft_fail: false

  docker:
    runs-on: ubuntu-latest
    needs: scan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Image
        run: |
          docker build -t $ECR_REGISTRY/$BACKEND_REPO:$IMAGE_TAG ./server

      - name: Build Frontend Image
        run: |
          docker build -t $ECR_REGISTRY/$FRONTEND_REPO:$IMAGE_TAG ./client

      - name: Trivy Backend Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: $ECR_REGISTRY/$BACKEND_REPO:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Trivy Frontend Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: $ECR_REGISTRY/$FRONTEND_REPO:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Push Backend Image
        run: docker push $ECR_REGISTRY/$BACKEND_REPO:$IMAGE_TAG

      - name: Push Frontend Image
        run: docker push $ECR_REGISTRY/$FRONTEND_REPO:$IMAGE_TAG

  approval:
    runs-on: ubuntu-latest
    needs: docker
    environment:
      name: production 

    steps:
      - name: Approval Step
        run: echo "you want to deploy new version"

  deploy:
    runs-on: ubuntu-latest
    needs: approval

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Backend Image in Rollout
        run: |
          sed -i "s|image: .*backend:.*|image: $ECR_REGISTRY/$BACKEND_REPO:$IMAGE_TAG|g" \
          k8/backend/backend-rollout.yaml

      - name: Update Frontend Image in Rollout
        run: |
          sed -i "s|image: .*frontend:.*|image: $ECR_REGISTRY/$FRONTEND_REPO:$IMAGE_TAG|g" \
          k8/frontend/frontend-rollout.yaml


      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      - name: Deploy Rollouts
        run: |
          kubectl apply -f k8/backend/backend-rollout.yaml
          kubectl apply -f k8/frontend/frontend-rollout.yaml

  approval-prod:
    runs-on: ubuntu-latest
    needs: deploy
    environment:
      name: production   

    steps:
      - run: echo "you want to deploy new version to public"


  promote:
    runs-on: ubuntu-latest
    needs: approval-prod

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        
      - name: Install Argo Rollouts CLI
        run: |
          curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64
          chmod +x kubectl-argo-rollouts-linux-amd64
          mv kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts

      - name: Setup kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $CLUSTER_NAME

      - name: Promote Backend
        run: kubectl argo rollouts promote backend

      - name: Promote Frontend
        run: kubectl argo rollouts promote frontend

  dast:
    runs-on: ubuntu-latest
    needs: promote

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Full Scan (Docker)
        run: |
          docker run --rm \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py \
            -t https://k8s-mernprod-mern-2a3b4c5d6e.us-east-1.elb.amazonaws.com \
            -r zap-report.html 

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-full-scan-report
          path: |
            zap-report.html